### ISSUE TITLE
기본 기능 TODO LIST

### ISSUE THREAD

**Issue by ssssooyoung** [ssssooyoung/aap#3]
- [x] 단축키, 휠 이벤트 옵션으로 빼기 (실행 파라미터로)
- [x] Zoom In/Out 버튼으로 만들기
- [x] 로딩 애니메이션 만들기
- [x] 컨트롤러 영역 스타일링 하기
- [x] 맨 앞으로 이동하는 버튼 만들기
- [x] 입력받은 mp3 파일로 파형을 그린다.
- [x] 타임라인을 표시한다
- [x] 마우스 휠 이벤트로 ZoomIn/ZoomOut 을 한다.
- [x] Play/Pause 버튼을 추가한다.
- [x] 1초 단위 이동 버튼을 추가한다.
- [x] 위 두 기능에 해당하는 단축키
- [x] 실행 화면에서 기본 포커스가 플레이어로 되어 있게 만들기.
- [x] 볼륨 조정 기능 추가.
- [x] 볼륨 슬라이더 위에서 휠 정리돌려서 볼륨 조정 되게 만들기.
- [x] 현재 재생 시간 표시.
- [x] 재생 길이 시간 표시.
- ~~[x] mouseover에 따른 커서 위치를 표시한다~~
